version: '2'
services:
  web:
    image: robertdebock/docker-rundeck-httpd
    ports:
      - 8080:80
    depends_on:
      - rundeck
    links:
      - rundeck
  rundeck:
    image: robertdebock/docker-rundeck:mysql
    volumes:
      - /var/log/rundeck
      - /var/rundeck
    environment:
      URL: http://192.168.99.100
      PORT: 8008
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rundeck
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
