version: '2'
services:
  frontend:
    image: robertdebock/docker-rundeck-httpd
    ports:
      - 8080:80
    depends_on:
      - rundeck
    links:
      - rundeck
  application:
    image: robertdebock/docker-rundeck:mysql
    ports:
      - "4440:4440"
    volumes:
      - /var/log/rundeck
      - /var/rundeck
    environment:
      URL: http://192.168.99.100
    depends_on:
      - datalayer
    links:
      - mysql
  datalayer:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rundeck
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
