version: '2'
services:
  web:
    build: ../docker-rundeck-httpd/
    ports:
      - 8080:80
    depends_on:
      - rundeck
    links:
      - rundeck
  rundeck:
    build: ../docker-rundeck
    environment:
      HOST: 192.168.99.100
      PORT: 8080
      URL: http://192.168.99.100:8080/rundeck
      MYSQL_DATABASE: rundeck
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: rundeck
      MYSQL_USER: rundeck
    volumes:
      - /var/log/rundeck
      - /var/rundeck
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rundeck
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
