version: '2'
services:
  web:
    image: robertdebock/docker-rundeck-httpd
    env_file: "variables.env"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rundeck
    links:
      - rundeck
  rundeck:
    image: robertdebock/docker-rundeck
    container_name: rundeck
    env_file: "variables.env"
    volumes:
      - /var/log/rundeck
      - /var/rundeck
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    env_file: "variables.env"
    volumes:
      - /var/lib/mysql
