version: '2'
services:
  web:
    image: robertdebock/docker-rundeck-httpd
    ports:
      - 8080:80
    depends_on:
      - rundeck
    links:
      - rundeck
  rundeck:
    image: robertdebock/docker-rundeck
    environment:
      HOST: 192.168.99.100
      URL: http://192.168.99.100:8080/rundeck
    volumes:
      - ~/Documents/rundeck/var/log/rundeck:/var/log/rundeck
      - ~/Documents/rundeck/var/rundeck:/var/rundeck
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rundeck
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
    volumes:
      - ~/Documents/mysql/var/lib/mysql:/var/lib/mysql
      - ./fix-mysql-permissions.sh:/fix-mysql-permissions.sh
    command: "/fix-mysql-permissions.sh"
