version: '2'
services:
  web:
    image: robertdebock/docker-rundeck-httpd
    env_file: "variables.env"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rundeck
    links:
      - rundeck
  rundeck:
    image: robertdebock/docker-rundeck
    env_file: "variables.env"
    volumes:
      - ~/Documents/rundeck/var/log/rundeck:/var/log/rundeck
      - ~/Documents/rundeck/var/rundeck:/var/rundeck
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    env_file: "variables.env"
    volumes:
      - ~/Documents/mysql/var/lib/mysql:/var/lib/mysql
#      - ./fix-mysql-permissions.sh:/fix-mysql-permissions.sh
#    command: "/fix-mysql-permissions.sh"
