version: '2'
services:
  web:
    image: robertdebock/docker-rundeck-httpd
    ports:
      - 8080:80
    depends_on:
      - rundeck
    links:
      - rundeck
  rundeck:
    image: robertdebock/docker-rundeck:mysql
    environment:
      CONTEXT: rundeck
      HOST: 192.168.99.100
      MYSQL_DATABASE: rundeck
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: rundeck
      MYSQL_USER: rundeck
      NAME: RUNDECK
      PORT: 8080
      PROTOCOL: http
    volumes:
      - /var/log/rundeck
      - /var/rundeck
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rundeck
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck
